#!/usr/bin/env node
/**
 * Reads every idl/*.json and emits src/generated/<program>.ts with a typed
 * IDL constant.  Safe to re-run (idempotent).
 */
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const idlDir = join(__dirname, '..', 'idl');
const generatedDir = join(__dirname, '..', 'src', 'generated');

mkdirSync(generatedDir, { recursive: true });

/** bazaar_registry → BazaarRegistry */
function toPascalCase(name) {
  return name
    .split('_')
    .map((w) => w[0].toUpperCase() + w.slice(1))
    .join('');
}

/** bazaar_registry → bazaar-registry */
function toKebabCase(name) {
  return name.replace(/_/g, '-');
}

/** Rejects names that could escape the output directory or inject into TS template literals. */
function assertSafeProgramName(name) {
  if (!/^[a-z][a-z0-9_]*$/.test(name)) {
    throw new Error(`Refusing to codegen: unsafe program name ${JSON.stringify(name)}`);
  }
}

const idlFiles = readdirSync(idlDir).filter((f) => f.endsWith('.json'));

for (const file of idlFiles) {
  const idl = JSON.parse(readFileSync(join(idlDir, file), 'utf-8'));
  const programName = idl.metadata?.name ?? file.replace('.json', '');
  assertSafeProgramName(programName);
  const typeName = toPascalCase(programName);
  const kebabName = toKebabCase(programName);

  // Biome organizeImports: value imports before type-only imports.
  const content = [
    `// Auto-generated by scripts/codegen.mjs — do not edit manually.`,
    `// Re-run: pnpm -F @agent-bazaar/idl run codegen`,
    `// Source: idl/${file}`,
    ``,
    `import idlJson from '../../idl/${file}' with { type: 'json' };`,
    `import type { ${typeName} } from '../${kebabName}.js';`,
    ``,
    `export type { ${typeName} };`,
    ``,
    `/** Typed IDL constant for use with \`new Program<${typeName}>(IDL, connection)\`. */`,
    `export const IDL: ${typeName} = idlJson as unknown as ${typeName};`,
    ``,
  ].join('\n');

  writeFileSync(join(generatedDir, `${kebabName}.ts`), content, 'utf-8');
  console.log(`  generated: src/generated/${kebabName}.ts`);
}
